feat: try using swc to parse the CSS AST
postcss/postcss-at-rule-parser pull request #3
Opened 2022-08-10 15:14 UTC by yisibl

2022-08-11 03:50 UTC, CGQAQ requested changes
`swc-css-parser` may be confusing when there's also a crate called `swc_css_parser`

2022-08-11 03:50 UTC, CGQAQ commented on Cargo.toml
> +name = "swc-css-parser"
```suggestion
name = "swc-css-parser-glue"
```

2022-08-11 03:50 UTC, CGQAQ commented on Cargo.toml
> +description = "SWC CSS parser"
```suggestion
description = "SWC CSS parser glue code for WASM"
```

2022-08-11 04:25 UTC, yisibl commented on Cargo.toml
> +name = "swc-css-parser"
Thanks!

2022-08-11 04:28 UTC, merged

2022-09-27 02:48 UTC, g-plane commented
It looks like some code are copied from https://github.com/g-plane/swc-css-playground . If it's true, please consider add a note in comments about the original code.

2022-09-28 14:32 UTC, yisibl commented
@g-plane No problem.